export const FETCH_PLACES = 'FETCH_PLACES';
export const UPDATE_SELECTED_PLACE = 'UPDATE_SELECTED_PLACE';
export const SELECT_FILTER_TYPE = 'SELECT_FILTER_TYPE';
export const SELECT_FILTER_DATA = 'SELECT_FILTER_DATA';